BEGIN;
DROP TABLE IF EXISTS pi_session_log;
DROP TABLE IF EXISTS pi_sessions;
DROP TABLE IF EXISTS pi_memories;
DROP TABLE IF EXISTS provider_keys;
DROP TABLE IF EXISTS project_messages;
DROP TABLE IF EXISTS project_snapshots;
DROP TABLE IF EXISTS project_public_snapshot_bindings;
DROP TABLE IF EXISTS canonical_public_repository_snapshots;
DROP TABLE IF EXISTS traces;
DROP TABLE IF EXISTS owner_quota_events;
DROP TABLE IF EXISTS analysis_jobs;
DROP TABLE IF EXISTS provider_settings;
DROP TABLE IF EXISTS learner_profiles;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS app_users;
DELETE FROM schema_migrations WHERE version = '0001_product';
DROP TABLE IF EXISTS schema_migrations;
COMMIT;
