BEGIN;
-- Build data without touching the published pointer or the analysis lease row.
CREATE TABLE snapshot_directory_generations (
  directory_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_snapshot_key text NOT NULL,
  snapshot_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(directory_id, public_snapshot_key, snapshot_id)
);
INSERT INTO snapshot_directory_generations(directory_id, public_snapshot_key, snapshot_id)
  SELECT directory_id, public_snapshot_key, snapshot_id FROM snapshot_query_directories;
SELECT setval(pg_get_serial_sequence('snapshot_directory_generations','directory_id'),
  GREATEST(COALESCE((SELECT max(directory_id) FROM snapshot_directory_generations),0),1),
  EXISTS(SELECT 1 FROM snapshot_directory_generations));
CREATE INDEX snapshot_directory_generations_public_key_idx
  ON snapshot_directory_generations(public_snapshot_key);
-- Add/validate the deferred FK after backfill and index DDL. Otherwise the
-- backfill queues trigger events which PostgreSQL refuses to combine with DDL.
ALTER TABLE snapshot_directory_generations ADD CONSTRAINT snapshot_directory_generations_snapshot_fk
  FOREIGN KEY(public_snapshot_key) REFERENCES canonical_public_repository_snapshots(public_snapshot_key)
  ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE snapshot_query_directories ALTER COLUMN directory_id DROP IDENTITY;
ALTER TABLE snapshot_query_directories ADD CONSTRAINT snapshot_directory_published_generation_fk
  FOREIGN KEY(directory_id, public_snapshot_key, snapshot_id)
  REFERENCES snapshot_directory_generations(directory_id, public_snapshot_key, snapshot_id)
  DEFERRABLE INITIALLY DEFERRED;
DO $$
DECLARE suffix text; constraint_row record;
BEGIN
  FOREACH suffix IN ARRAY ARRAY['nodes','edges','evidence','evidence_links','layers','value_points','overlay_memberships','projection_nodes','projection_edges'] LOOP
    FOR constraint_row IN SELECT conname FROM pg_constraint
      WHERE conrelid=('snapshot_directory_'||suffix)::regclass
        AND contype='f' AND confrelid='snapshot_query_directories'::regclass LOOP
      EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I','snapshot_directory_'||suffix,constraint_row.conname);
    END LOOP;
    EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY(directory_id) REFERENCES snapshot_directory_generations(directory_id) ON DELETE CASCADE',
      'snapshot_directory_'||suffix,'snapshot_directory_'||suffix||'_generation_fk');
  END LOOP;
END $$;
-- Preserve existing non-owner runtime/read-only grants, including sequence use.
DO $$
DECLARE entry record; grantee_name text;
BEGIN
  FOR entry IN SELECT a.* FROM pg_class c
    CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl,acldefault('r',c.relowner))) a
    WHERE c.oid='snapshot_query_directories'::regclass LOOP
    grantee_name := CASE WHEN entry.grantee=0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(entry.grantee)) END;
    EXECUTE format('GRANT %s ON snapshot_directory_generations TO %s%s',entry.privilege_type,grantee_name,
      CASE WHEN entry.is_grantable THEN ' WITH GRANT OPTION' ELSE '' END);
    IF entry.privilege_type='INSERT' THEN
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO %s',pg_get_serial_sequence('snapshot_directory_generations','directory_id'),grantee_name);
    END IF;
  END LOOP;
END $$;
INSERT INTO schema_migrations(version) VALUES ('0025_snapshot_directory_generations');
COMMIT;
