import type { ActivityIconName } from './ActivityIcon';

// Display contract prepared for future backend progress events. These entries do
// not emit events or infer progress from timers.
export const detailedAnalysisStages = [
  { id: 'waiting_resources', reviewId: 'F19', title: '等待处理资源', icon: 'wait',
    running: '任务已接收，正在等待可用处理资源', completed: '已轮到此任务，继续分析',
    runningEn: 'Task accepted; waiting for available processing resources', completedEn: 'Resources available; analysis continuing',
    description: '任务在阶段之间等待资源；保留已完成的结果，获得资源后继续。' },
  { id: 'researching_project', reviewId: 'F01', title: '查找项目资料', icon: 'research',
    running: '正在查找项目资料', completed: '项目资料查询完成',
    runningEn: 'Looking up project background', completedEn: 'Project background lookup complete',
    description: '查询项目的架构和设计资料，供后续价值点分析参考。分阶段运行时在语义阶段查询；资料不可用时应显示跳过，不能声称已经找到。' },
  { id: 'parsing_source', reviewId: 'F02', title: '静态解析源码', icon: 'inspect',
    running: '正在解析源码结构', completed: '源码结构解析完成',
    runningEn: 'Parsing source structure', completedEn: 'Source structure parsed',
    description: '从源码中提取文件、符号和语法结构；增量分析可以复用未变文件的结果。这一步由程序完成。' },
  { id: 'resolving_relations', reviewId: 'F03', title: '识别调用与引用', icon: 'connections',
    running: '正在识别调用与引用', completed: '调用与引用识别完成',
    runningEn: 'Resolving calls and references', completedEn: 'Calls and references resolved',
    description: '结合 TypeScript 语义绑定和可用的语言工具，确认符号之间的调用、引用等关系；具体能力取决于仓库语言。' },
  { id: 'building_fact_graph', reviewId: 'F04', title: '建立基础图谱', icon: 'components',
    running: '正在建立代码基础图谱', completed: '代码基础图谱已建立',
    runningEn: 'Building the code fact graph', completedEn: 'Code fact graph built',
    description: '将静态事实整理为组件、关系、证据索引和基础视图。模型随后解释这些已有事实，不重新发明组件边界。' },
  { id: 'explaining_components', reviewId: 'F05', title: '模型讲解组件', icon: 'explain',
    running: '正在分析组件职责', completed: '组件职责分析完成',
    runningEn: 'Explaining component responsibilities', completedEn: 'Component responsibilities explained',
    description: '模型分批阅读组件材料、按需查代码，生成名称、职责和归组说明。同一阶段可以有多个并行批次。' },
  { id: 'repairing_components', reviewId: 'F06', title: '补全组件讲解', icon: 'mend',
    running: '正在补全组件讲解', completed: '组件讲解补全完成',
    runningEn: 'Filling gaps in component explanations', completedEn: 'Component explanation gaps addressed',
    description: '只在部分组件缺少有效讲解时出现，重新核对所需代码并补充说明。仍有缺口时应显示部分完成，不假装全部成功。' },
  { id: 'planning_architecture', reviewId: 'F07', title: '模型归纳架构', icon: 'layers',
    running: '正在归纳架构层与分组', completed: '架构层与分组归纳完成',
    runningEn: 'Organizing architecture layers and groups', completedEn: 'Architecture layers and groups organized',
    description: '组件讲解完成后，模型结合全局材料归纳架构层、职责和分组。大输入可能先分批归纳，再统一收口；与价值点挖掘并行。' },
  { id: 'discovering_values', reviewId: 'F08', title: '模型挖掘价值点', icon: 'discovery',
    running: '正在挖掘值得学习的设计', completed: '值得学习的设计已整理',
    runningEn: 'Finding designs worth learning from', completedEn: 'Notable design lessons organized',
    description: '结合组件讲解、仓库代码和可用的外部资料，核对设计要解决的问题、实现、代价与迁移条件；与架构归纳并行，不等待最终分层。' },
  { id: 'assembling_architecture', reviewId: 'F09', title: '组装架构视图', icon: 'map',
    running: '正在组装架构视图', completed: '架构视图组装完成',
    runningEn: 'Assembling the architecture view', completedEn: 'Architecture view assembled',
    description: '程序将已核对的组件讲解和层级建议装配到图上，处理分组与降级项。这是架构分支的收尾，不是新的模型绘图请求。' },
  { id: 'merging_analysis', reviewId: 'F10', title: '汇合分析结果', icon: 'merge',
    running: '正在整合架构与价值点', completed: '架构与价值点已整合',
    runningEn: 'Combining architecture and learning insights', completedEn: 'Architecture and learning insights combined',
    description: '等架构分支和价值点分支结束，将两份结果汇入同一份分析快照；此时还没有发布为可用结果。' },
  { id: 'preparing_source', reviewId: 'F11', title: '准备源码阅读材料', icon: 'files',
    running: '正在准备源码阅读材料', completed: '源码阅读材料已准备',
    runningEn: 'Preparing source files for reading', completedEn: 'Source files ready for reading',
    description: '将源码准备为受控阅读对象。分阶段运行时在发布阶段处理，本地存储不一定有此独立步骤。' },
  { id: 'validating_analysis', reviewId: 'F12', title: '校验证据与结果', icon: 'verify',
    running: '正在核对分析结果与证据', completed: '分析结果与证据核对完成',
    runningEn: 'Checking analysis results against evidence', completedEn: 'Analysis results and evidence checked',
    description: '补充版本沿革信息、分离显示语言，并检查快照结构与证据引用。校验失败不能进入成功状态。' },
  { id: 'publishing_analysis', reviewId: 'F13', title: '保存并提供完整结果', icon: 'archive',
    running: '正在保存完整分析结果', completed: '完整分析结果已就绪',
    runningEn: 'Saving the complete analysis', completedEn: 'Complete analysis ready',
    description: '保存基础快照、显示语言、来源索引和任务状态，关联到项目后才显示就绪。已有可用结果时可能直接复用，不经过上述全部步骤。' },
  { id: 'translating_components', reviewId: 'F14', title: '翻译组件讲解', icon: 'translate',
    running: '正在翻译组件讲解', completed: '组件讲解翻译完成',
    runningEn: 'Translating component explanations', completedEn: 'Component explanations translated',
    description: '仅补充缺少的显示语言时出现；按批翻译已有组件名称与职责，保留稳定标识和证据，不重新分析源码。' },
  { id: 'translating_layers', reviewId: 'F15', title: '翻译架构层说明', icon: 'layers',
    running: '正在翻译架构层说明', completed: '架构层说明翻译完成',
    runningEn: 'Translating architecture layer descriptions', completedEn: 'Architecture layer descriptions translated',
    description: '语言补充任务的后续步骤：翻译已有架构层的名称和职责，不改变架构层归属。' },
  { id: 'translating_relations', reviewId: 'F16', title: '翻译关系说明', icon: 'connections',
    running: '正在翻译关系说明', completed: '关系说明翻译完成',
    runningEn: 'Translating relationship descriptions', completedEn: 'Relationship descriptions translated',
    description: '语言补充任务：翻译关系类型的标签和说明，保留真实关系与方向。' },
  { id: 'translating_values', reviewId: 'F17', title: '翻译价值点说明', icon: 'discovery',
    running: '正在翻译价值点说明', completed: '价值点说明翻译完成',
    runningEn: 'Translating learning insight descriptions', completedEn: 'Learning insight descriptions translated',
    description: '语言补充任务：翻译已有价值点及其说明，不新做一轮价值点挖掘。缺失译文应保留降级标记。' },
  { id: 'publishing_translation', reviewId: 'F18', title: '保存新的语言版本', icon: 'save',
    running: '正在保存新的语言版本', completed: '新的语言版本已就绪',
    runningEn: 'Saving the new language version', completedEn: 'New language version ready',
    description: '翻译批次结束后保存语言版本并更新可用状态；存在缺口时按部分可用处理，不强行标记完整。' },
] as const satisfies ReadonlyArray<{
  id: string; reviewId: string; title: string; icon: ActivityIconName;
  running: string; completed: string; runningEn: string; completedEn: string; description: string;
}>;

export type DetailedAnalysisStageId = typeof detailedAnalysisStages[number]['id'];
